services:
  generator:
    build:
      context: .
      dockerfile: ./generator/Dockerfile
    volumes:
      - ./shared:/shared
    environment:
      INPUT_FILES_PATH: /shared/parquet
  dbt:
    build:
      context: .
      dockerfile: ./dbt/Dockerfile
    volumes:
      - ./shared:/shared
      - ./dbt/postcard_company:/datamart/postcard_company
    environment:
      INPUT_FILES_PATH: /shared/parquet  
  dagster:
    build:
      context: .
      dockerfile: ./dagster/Dockerfile
    restart: always
    environment:
        DUCKDB_FILE_PATH: /shared/db/datamart.duckdb
        INPUT_FILES_PATH: /shared/parquet
    volumes:
        - ./shared:/shared
        - ./dbt/postcard_company:/postcard_company
    ports:
        - "3000:3000"
    depends_on:
      generator:
        condition: service_completed_successfully
      dbt:
        condition: service_completed_successfully
  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        SUPERSET_ADMIN: $SUPERSET_ADMIN
        SUPERSET_PASSWORD: $SUPERSET_PASSWORD
        SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
        - "8088:8088"
    command:     gunicorn --bind  "0.0.0.0:8088" --access-logfile '-' --error-logfile '-' --workers 1 --worker-class gthread --threads 20 --timeout 60 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
    post_start:
      - command: "superset import-dashboards -p ./dashboard.zip -u ${SUPERSET_ADMIN}"
    volumes:
      - ./shared/db:/app/superset_home/db
    depends_on:
      - dagster
